(function (global) {
  'use strict';

  var NAMES = { boss: 'Boss', jane: 'Jane', cho: 'Cho', rigsby: 'Rigsby', lisbon: 'Lisbon', vanpelt: 'Van Pelt' };
  var DUTY_PRESETS = [
    { type: 'boss', name: 'Boss', color: '#B08A5A' },
    { type: 'jane', name: 'Jane', color: '#5BA66B' },
    { type: 'cho', name: 'Cho', color: '#68747A' },
    { type: 'rigsby', name: 'Rigsby', color: '#7E9AB0' },
    { type: 'lisbon', name: 'Lisbon', color: '#A06F62' },
    { type: 'vanpelt', name: 'Van Pelt', color: '#B48A9B' }
  ];
  var COLORS = ['#8D7BE8', '#6C57D7', '#D85A30', '#E84A7A', '#E8B96A', '#C99E3F', '#9B6BCC', '#4AADE8', '#3D8FD1', '#58A675', '#3E8E58', '#6B8AFF', '#4668D9', '#888888', '#B0835E', '#4CC4C0'];
  var COLLAPSE_KEY = 'cbi_shop_collapsed_v2';
  var db = null;
  var collapsed = {};
  var editProjectId = '';
  var editItemProjectId = '';
  var editItemId = '';
  var sectionDrafts = [];
  var dutyDraft = { type: '', name: '', color: '#E8B96A' };
  var projectIconDraft = '';
  var projectIconPosition = { x: 50, y: 50 };
  var itemImageDraft = '';
  var iconDrag = null;
  var shopSwipeStart = null;
  var toastTimer = null;

  function esc(value) {
    return String(value == null ? '' : value)
      .replace(/&/g, '&amp;').replace(/</g, '&lt;').replace(/>/g, '&gt;')
      .replace(/"/g, '&quot;').replace(/'/g, '&#39;');
  }
  function clamp(value, min, max) { return Math.max(min, Math.min(max, Number(value) || 0)); }
  function gid(prefix) { return global.CBIData.createId(prefix || 'shop'); }
  function projects() { return db.work.shop.projects || []; }
  function projectById(id) { return projects().find(function (project) { return project.id === id; }) || null; }
  function itemById(project, id) { return project && project.items.find(function (item) { return item.id === id; }) || null; }
  function isOwned(id) { return db.work.shop.owned.indexOf(id) >= 0; }
  function walletDb() { try { return JSON.parse(global.localStorage.getItem('wallet_db')) || {}; } catch (error) { return {}; } }
  function availableFund() { return global.CBIData.availableShopFund(db, walletDb()); }
  function save() { db = global.CBIData.save(db) || db; }
  function projectColor(project) { return project.duty && project.duty.color || project.color || '#E8B96A'; }
  function dutyName(project) {
    var duty = project.duty || {};
    var preset = DUTY_PRESETS.find(function (item) { return item.type === duty.type; });
    return preset ? preset.name : (duty.name || '');
  }
  function today() { return new Date().toISOString().slice(0, 10); }
  function loadCollapsed() {
    try { var value = JSON.parse(global.localStorage.getItem(COLLAPSE_KEY) || '{}'); return value && typeof value === 'object' ? value : {}; }
    catch (error) { return {}; }
  }
  function saveCollapsed() { try { global.localStorage.setItem(COLLAPSE_KEY, JSON.stringify(collapsed)); } catch (error) {} }

  function injectStyles() {
    if (document.getElementById('cbiFoodShopStyles')) return;
    var style = document.createElement('style'); style.id = 'cbiFoodShopStyles';
    style.textContent = `
*{margin:0;padding:0;box-sizing:border-box;-webkit-tap-highlight-color:transparent}
body[data-cbi-shop="3"]{font-family:-apple-system,BlinkMacSystemFont,"SF Pro Text","Helvetica Neue",sans-serif;background:#FAFAFA;color:#1a1a1a;min-height:100vh;min-height:100dvh;padding-bottom:72px}
body[data-cbi-shop="3"] button,body[data-cbi-shop="3"] input,body[data-cbi-shop="3"] textarea,body[data-cbi-shop="3"] select{font-family:inherit}
.top-bar{display:grid;grid-template-columns:minmax(0,1fr) auto minmax(0,1fr);align-items:center;padding:16px 20px;padding-top:env(safe-area-inset-top,24px);border-bottom:1px solid #eee;background:#fff;position:sticky;top:0;z-index:50}.top-bar h1{font-size:15px;font-weight:600;letter-spacing:2px;color:#8B6914;text-align:center}.top-bar>:first-child{justify-self:start}.top-bar>:last-child{justify-self:end}.back-btn{font-size:13px;color:#999;text-decoration:none;cursor:pointer;background:none;border:none;padding:4px}.btn-s{font-size:11px;color:#999;background:none;border:1px solid #ddd;border-radius:6px;padding:5px 10px;cursor:pointer}
.shop-fund-strip{padding:8px 20px;display:flex;align-items:center;justify-content:space-between;gap:12px;background:#fff;border-bottom:1px solid #f5f5f5;color:#bbb;font-size:10px;letter-spacing:.25px}.shop-fund-strip strong{font-weight:500;color:#9B7D41;font-variant-numeric:tabular-nums}
.project-list{padding:8px 0}.project-category-header{width:100%;display:flex;align-items:center;gap:10px;padding:10px 20px;background:#fafafa;border:0;border-bottom:1px solid #f0f0f0;cursor:pointer;user-select:none}.project-category-header:active{background:#f5f5f5}.project-category-line{flex:1;height:1px;background:#e0e0e0}.project-category-label{font-size:11px;color:#999;font-weight:500;letter-spacing:.3px;white-space:nowrap;overflow:hidden;text-overflow:ellipsis;max-width:55vw}.project-category-arrow{font-size:8px;color:#ccc;transition:transform .25s;width:8px;flex-shrink:0}.project-category-header.collapsed .project-category-arrow{transform:rotate(-90deg)}.project-category-items{display:grid;grid-template-rows:1fr;overflow:hidden;transition:grid-template-rows .3s ease,opacity .25s ease;opacity:1}.project-category-items>div{min-height:0}.project-category-items.collapsed{grid-template-rows:0fr;opacity:0;pointer-events:none}
.project-row{display:flex;align-items:center;gap:14px;padding:14px 20px;background:#fff;border-bottom:1px solid #f5f5f5;position:relative}.project-icon-wrap{width:44px;height:44px;border-radius:12px;overflow:hidden;display:flex;align-items:center;justify-content:center;background:#FFF8E6;flex-shrink:0}.project-icon-wrap img{width:100%;height:100%;object-fit:cover}.project-icon-wrap .emoji-fb{font-size:22px}.project-row-body{flex:1;min-width:0}.project-row-top{display:flex;align-items:center;gap:6px;margin-bottom:2px}.project-row-name{font-size:14px;font-weight:500;color:#333}.project-row-meta{font-size:11px;color:#bbb;display:flex;align-items:center;gap:8px}.project-row-progress{flex:1;max-width:120px;height:3px;background:#f0f0f0;border-radius:2px;overflow:hidden}.project-row-fill{height:100%;border-radius:2px;transition:width .3s}.project-row-pct{font-size:10px;color:#ccc;font-variant-numeric:tabular-nums;min-width:28px;text-align:right}.project-complete-star{font-size:12px;color:#E8B96A;flex-shrink:0}.duty-badge{font-size:9px;font-weight:500;letter-spacing:.5px;display:inline-block;padding:1px 6px;border-radius:4px}.project-edit-btn{flex:0 0 auto;border:0;background:none;color:#bbb;font-size:16px;padding:8px 2px 8px 8px;cursor:pointer}.project-row-add{display:flex;align-items:center;justify-content:center;padding:14px 20px;background:#fff;border:0;border-bottom:1px solid #f5f5f5;cursor:pointer;font-size:13px;color:#ccc;width:100%}
.shop-inline-detail{background:#fff;border-bottom:1px solid #eee;padding-bottom:4px}.section-divider{display:flex;align-items:center;gap:10px;padding:10px 20px;background:#fafafa;border-bottom:1px solid #f0f0f0}.section-divider-line{flex:1;height:1px;background:#e0e0e0}.section-divider-center{display:flex;flex-direction:column;align-items:center;gap:1px;flex-shrink:0}.section-divider-label{font-size:11px;color:#999;font-weight:500;letter-spacing:.3px}.section-progress{font-size:9px;color:#c5c5c5;white-space:nowrap;font-variant-numeric:tabular-nums;letter-spacing:.3px}.section-type-badge{font-size:9px;padding:1px 6px;border-radius:4px;margin-left:4px}.section-grid{display:grid;gap:8px;padding:8px 20px 16px}.item-cell{aspect-ratio:1;border-radius:10px;border:1.5px solid #e8e8e8;display:flex;flex-direction:column;align-items:center;justify-content:center;cursor:pointer;transition:all .15s;position:relative;overflow:hidden;background:#f5f5f5}.section-grid.one-column .item-cell{aspect-ratio:2/1}.item-cell:active{transform:scale(.97)}.item-cell .item-img{width:100%;height:100%;object-fit:contain;padding:5px;border-radius:9px;position:absolute;top:0;left:0;background:#fff;filter:grayscale(100%) brightness(.85);transition:filter .4s}.item-cell.collected{border-color:#E8B96A}.item-cell.collected .item-img{filter:none}.item-cell .item-num{font-size:20px;font-weight:200;color:#ddd;font-variant-numeric:tabular-nums;position:relative;z-index:1}.item-cell .item-label{position:absolute;bottom:0;left:0;right:0;background:linear-gradient(transparent,rgba(0,0,0,.5));color:#fff;font-size:10px;font-weight:500;padding:14px 5px 4px;border-radius:0 0 9px 9px;text-align:center;overflow:hidden;text-overflow:ellipsis;white-space:nowrap;z-index:1}.item-cell:not(.has-img) .item-label{background:none;color:#ccc;position:static;font-size:9px;padding:0 4px;margin-top:2px}.item-cell.collected:not(.has-img){background:#FFFDF7;border-color:#E8B96A}.item-cell.collected:not(.has-img) .item-num{color:#E8B96A}.item-check{position:absolute;top:4px;right:4px;width:18px;height:18px;border-radius:50%;background:rgba(232,185,106,.9);display:flex;align-items:center;justify-content:center;font-size:10px;color:#fff;z-index:2}.item-price{position:absolute;top:5px;left:5px;padding:2px 5px;border-radius:4px;background:rgba(255,255,255,.9);color:#9B7D41;font-size:8px;z-index:2}.add-item-btn{margin:0 20px 16px;padding:10px;border:1.5px dashed #ddd;border-radius:10px;background:#fff;font-size:12px;color:#aaa;cursor:pointer;text-align:center;width:calc(100% - 40px)}
.bottom-nav{position:fixed;bottom:0;left:0;right:0;display:flex;background:rgba(255,255,255,.94);-webkit-backdrop-filter:blur(16px);backdrop-filter:blur(16px);border-top:1px solid rgba(0,0,0,.06);z-index:60;padding:0 12px env(safe-area-inset-bottom,0)}.bottom-nav a{position:relative;flex:1;padding:15px 0 13px;color:#bbb;font-size:10px;letter-spacing:.25px;text-align:center;text-decoration:none}.bottom-nav a.active{color:#4e4a44}.bottom-nav a.active:before{content:"";position:absolute;left:36%;right:36%;top:0;height:1px;background:#9c907c}
.modal-bg{position:fixed;inset:0;background:rgba(0,0,0,.3);z-index:200;display:none;align-items:flex-end;justify-content:center}.modal-bg.show{display:flex}.modal{background:#fff;border-radius:16px 16px 0 0;width:100%;max-width:480px;max-height:88vh;overflow-y:auto;padding:20px;animation:slideUp .25s ease-out}@keyframes slideUp{from{transform:translateY(100%)}to{transform:translateY(0)}}.modal h2{font-size:15px;font-weight:600;margin-bottom:16px;color:#333}.modal label{display:block;font-size:12px;color:#999;margin-bottom:4px;margin-top:12px}.modal input,.modal textarea,.modal select{width:100%;font-size:14px;padding:10px 12px;border:1px solid #e0e0e0;border-radius:8px;background:#fff;color:#1a1a1a}.modal textarea{resize:vertical;min-height:50px}.btn-row{display:flex;gap:8px;margin-top:20px}.btn{flex:1;padding:12px;border:none;border-radius:10px;font-size:14px;font-weight:500;cursor:pointer}.btn-primary{background:#1a1a1a;color:#fff}.btn-cancel{background:#f0f0f0;color:#666}.btn-del{background:#fff;color:#D85A30;border:1px solid #f0d0c0}.file-label{display:block;padding:10px 12px;border:1px dashed #ddd;border-radius:8px;text-align:center;color:#aaa;font-size:12px;cursor:pointer;margin-top:4px}.img-preview{width:100%;border-radius:8px;margin-top:8px;max-height:240px;object-fit:contain;background:#f7f7f7}.project-icon-editor{width:min(180px,100%);margin:8px auto 0}.project-icon-pos-frame{width:100%;aspect-ratio:1;border-radius:16px;overflow:hidden;position:relative;cursor:grab;touch-action:none;border:1px solid #eee;background:#f7f7f7}.project-icon-pos-frame:active{cursor:grabbing}.project-icon-pos-frame img{width:100%;height:100%;object-fit:cover;display:block;pointer-events:none;user-select:none}.project-icon-clear{position:absolute;top:6px;right:6px;width:22px;height:22px;border-radius:50%;border:none;background:rgba(0,0,0,.45);color:#fff;font-size:12px;cursor:pointer;line-height:22px;text-align:center;z-index:2}.banner-pos-hint{display:flex;align-items:center;justify-content:space-between;margin-top:5px}.banner-pos-hint-text{font-size:10px;color:#bbb}.banner-pos-reset{font-size:10px;color:#aaa;background:none;border:1px solid #e0e0e0;border-radius:6px;padding:2px 8px;cursor:pointer}
.duty-row{display:flex;gap:5px;flex-wrap:wrap;margin-top:4px}.duty-opt{padding:3px 9px;border-radius:6px;border:1.5px solid #e0e0e0;font-size:11px;cursor:pointer;background:#fff;transition:all .15s}.duty-opt.active{border-width:2px}.duty-custom-row{display:flex;gap:5px;align-items:center;margin-top:6px;flex-wrap:wrap}.duty-custom-row input{flex:1 1 160px;min-width:140px;font-size:12px;padding:6px 8px}.color-picker-row{display:flex;gap:3px;align-items:center;flex-wrap:wrap}.color-swatch{width:14px;height:14px;border-radius:50%;cursor:pointer;border:1.5px solid transparent}.color-swatch.active{border-color:#333}
.section-list{margin-top:8px}.section-row{display:flex;align-items:center;gap:6px;padding:8px 0;border-bottom:1px solid #f5f5f5;flex-wrap:wrap}.section-row>input[type="text"]{flex:1 1 90px;min-width:70px;font-size:12px;padding:6px 8px;border:1px solid #e8e8e8;border-radius:6px;background:#fff}.section-row .del-sec{font-size:11px;color:#d0d0d0;background:none;border:none;cursor:pointer;padding:4px}.add-section-btn{font-size:11px;color:#bbb;background:none;border:1px dashed #e0e0e0;border-radius:6px;padding:6px 12px;cursor:pointer;margin-top:6px;width:100%}.section-config{width:100%;padding:5px 0;margin-top:4px}.section-config-line{display:flex;align-items:center;gap:5px;flex-wrap:wrap}.section-config-line+.section-config-line{margin-top:5px}.section-config-label{font-size:10px;color:#aaa;white-space:nowrap}.section-config input[type="text"]{flex:1 1 96px;min-width:80px;font-size:12px;padding:5px 8px;border:1px solid #e8e8e8;border-radius:6px}.section-config input[type="number"]{width:42px;flex:0 0 42px;font-size:12px;padding:5px 4px;border:1px solid #e8e8e8;border-radius:6px;text-align:center}.section-config select{width:auto;min-width:52px;font-size:11px;padding:4px;border:1px solid #e8e8e8;border-radius:6px}.section-tag-palette{display:flex;gap:3px;align-items:center;flex-wrap:wrap}.section-tag-swatch{width:14px;height:14px;border-radius:50%;border:1.5px solid transparent;padding:0;cursor:pointer}.section-tag-swatch.active{border-color:#333}
.item-detail{text-align:center}.item-detail-preview{width:112px;aspect-ratio:1;margin:0 auto;border-radius:12px;overflow:hidden;background:#f5f5f5;display:flex;align-items:center;justify-content:center;color:#ccc;font-size:24px}.item-detail-preview img{width:100%;height:100%;object-fit:contain}.item-detail h3{font-size:16px;margin-top:13px}.item-detail-meta{font-size:10px;color:#aaa;margin-top:6px}.item-detail-note{font-size:12px;color:#777;line-height:1.7;text-align:left;border-top:1px solid #eee;margin-top:13px;padding-top:11px;white-space:pre-wrap}.fund-note{font-size:10px;color:#999;line-height:1.6;margin-top:11px;text-align:center}
.confirm-bg{position:fixed;inset:0;background:rgba(0,0,0,.3);z-index:300;display:none;align-items:center;justify-content:center}.confirm-bg.show{display:flex}.confirm-box{background:#fff;border-radius:16px;width:85%;max-width:320px;padding:24px 20px;text-align:center}.confirm-box p{font-size:14px;color:#333;margin-bottom:16px;line-height:1.5}.confirm-box .btn-row{justify-content:center}.confirm-box .btn{min-width:80px;flex:none;padding:10px 16px;font-size:13px}.toast{position:fixed;top:env(safe-area-inset-top,20px);left:50%;transform:translateX(-50%) translateY(-120%);background:rgba(30,30,30,.88);color:#fff;font-size:13px;padding:10px 20px;border-radius:10px;z-index:400;pointer-events:none;transition:transform .3s cubic-bezier(.34,1.3,.64,1),opacity .3s;opacity:0}.toast.show{transform:translateX(-50%) translateY(0);opacity:1}body[data-cbi-shop="3"] #liminalCloudBadgeHost.liminal-cloud-floating-host{bottom:calc(66px + env(safe-area-inset-bottom,0px))}@media(min-width:700px){.shop-inline-detail .section-grid{max-width:640px;margin:0 auto}.shop-inline-detail .add-item-btn{display:block;max-width:600px;margin-left:auto;margin-right:auto}}
`;
    document.head.appendChild(style);
  }

  function shell() {
    document.body.innerHTML = '<header class="top-bar"><a class="back-btn" href="index.html?p=5">← Home</a><h1>SHOP</h1><button class="btn-s" type="button" data-action="backup">备份</button></header><div class="shop-fund-strip"><span>娱乐账户 · 商城资金</span><strong id="shopFund">¥0</strong></div><main id="shopRoot"><div class="project-list" id="projectList"></div></main><nav class="bottom-nav" aria-label="Reality Wallet"><a href="wallet.html">记账</a><a href="wallet.html#reimbursement">报销</a><a class="active" href="shop.html">商城</a></nav>' + projectModalMarkup() + itemModalMarkup() + detailModalMarkup() + backupModalMarkup() + '<div class="toast" id="shopToast"></div><div class="confirm-bg" id="shopConfirm"><div class="confirm-box"></div></div>';
  }
  function projectModalMarkup() {
    return '<div class="modal-bg" id="projectModal"><div class="modal"><h2 id="projectModalTitle">添加项目</h2><label>项目图标</label><label class="file-label" for="projectIconInput">点击选择图片</label><input type="file" accept="image/*" id="projectIconInput" style="display:none"><div id="projectIconEditor" class="project-icon-editor" style="display:none"><div id="projectIconPosFrame" class="project-icon-pos-frame"><img id="projectIconPreview" src="" alt=""><button type="button" class="project-icon-clear" data-action="clear-project-icon">×</button></div><div class="banner-pos-hint"><span class="banner-pos-hint-text">拖动图片调整显示区域</span><button type="button" class="banner-pos-reset" data-action="reset-project-icon">恢复居中</button></div></div><label>项目名</label><input type="text" id="inputProjectName" placeholder="如：Rollbahn 收集"><label>项目分类（选填）</label><input type="text" id="inputProjectCategory" list="projectCategoryOptions" placeholder="如：本子类、领带类"><datalist id="projectCategoryOptions"></datalist><label>项目细分</label><div class="section-list" id="sectionList"></div><button class="add-section-btn" type="button" data-action="add-section">+ 添加分栏</button><label>备注（选填）</label><textarea id="inputProjectNote" placeholder="品牌、款式或收集范围…"></textarea><label>适合谁</label><div class="duty-row" id="dutyRow"></div><div class="duty-custom-row" id="dutyCustomRow" style="display:none"><input type="text" id="dutyCustomName" placeholder="其他对象"><div class="color-picker-row" id="colorPicker"></div></div><div class="btn-row"><button class="btn btn-cancel" type="button" data-close="projectModal">取消</button><button class="btn btn-del" id="projectDeleteBtn" type="button" data-action="delete-project" style="display:none">删除</button><button class="btn btn-primary" type="button" data-action="save-project">保存</button></div></div></div>';
  }
  function itemModalMarkup() {
    return '<div class="modal-bg" id="itemModal"><div class="modal"><h2 id="itemModalTitle">添加品目</h2><label>所属分类</label><select id="inputItemSection"></select><label>名称</label><input type="text" id="inputItemName" placeholder="品目名称"><label>备注（选填）</label><textarea id="inputItemNote" placeholder="颜色、尺寸或想买它的理由…"></textarea><label>金额（日元）</label><input type="number" id="inputItemPrice" min="0" step="1" placeholder="0"><label>照片</label><label class="file-label" for="itemImgInput">点击选择图片</label><input type="file" accept="image/*" id="itemImgInput" style="display:none"><img id="itemImgPreview" class="img-preview" style="display:none" alt=""><div class="btn-row"><button class="btn btn-cancel" type="button" data-close="itemModal">取消</button><button class="btn btn-del" id="itemDeleteBtn" type="button" data-action="delete-item" style="display:none">删除</button><button class="btn btn-primary" type="button" data-action="save-item">保存</button></div></div></div>';
  }
  function detailModalMarkup() { return '<div class="modal-bg" id="itemDetailModal"><div class="modal"><h2 id="itemDetailTitle">品目</h2><div id="itemDetailBody"></div><div class="btn-row" id="itemDetailActions"></div></div></div>'; }
  function backupModalMarkup() { return '<div class="modal-bg" id="backupModal"><div class="modal"><h2>商城备份</h2><p style="font-size:11px;color:#999;line-height:1.7">导入与导出只处理商城的项目、品目和获得记录。</p><div class="btn-row"><button class="btn btn-cancel" type="button" data-close="backupModal">关闭</button><button class="btn btn-cancel" type="button" data-action="import-shop">导入</button><button class="btn btn-primary" type="button" data-action="export-shop">导出</button></div><input type="file" id="shopImportInput" accept=".json,application/json" style="display:none"></div></div>'; }

  function showToast(message) { var node = document.getElementById('shopToast'); node.textContent = message; node.classList.add('show'); clearTimeout(toastTimer); toastTimer = setTimeout(function () { node.classList.remove('show'); }, 2300); }
  function openModal(id) { document.getElementById(id).classList.add('show'); }
  function closeModal(id) { document.getElementById(id).classList.remove('show'); }
  function confirmBox(message, onYes, options) {
    var bg = document.getElementById('shopConfirm'); var box = bg.querySelector('.confirm-box');
    box.innerHTML = '<p>' + esc(message) + '</p><div class="btn-row"><button class="btn btn-cancel" id="confirmNo">取消</button><button class="btn ' + (options && options.danger ? 'btn-del' : 'btn-primary') + '" id="confirmYes">' + esc(options && options.yes || '确定') + '</button></div>'; bg.classList.add('show');
    box.querySelector('#confirmNo').onclick = function () { bg.classList.remove('show'); }; box.querySelector('#confirmYes').onclick = function () { bg.classList.remove('show'); onYes(); };
  }
  function refreshFund() { var node = document.getElementById('shopFund'); if (node) node.textContent = '¥' + availableFund(); }
  function projectStats(project) { var total = project.items.length; var collected = project.items.filter(function (item) { return isOwned(item.id); }).length; return { total: total, collected: collected, percent: total ? Math.round(collected / total * 100) : 0 }; }
  function sortedProjects() { return projects().slice().sort(function (a, b) { return (a.order || 0) - (b.order || 0); }); }
  function iconMarkup(project) { return project.icon ? '<img src="' + esc(project.icon) + '" alt="" style="object-position:' + clamp(project.iconPositionX, 0, 100) + '% ' + clamp(project.iconPositionY, 0, 100) + '%">' : '<div class="emoji-fb">◇</div>'; }

  function render() {
    refreshFund(); var groups = {}; sortedProjects().forEach(function (project) { var category = String(project.category || '').trim() || '未分类'; if (!groups[category]) groups[category] = []; groups[category].push(project); }); var html = '';
    Object.keys(groups).forEach(function (category) { var isCollapsed = collapsed[category] === true; html += '<button type="button" class="project-category-header' + (isCollapsed ? ' collapsed' : '') + '" data-action="toggle-category" data-category="' + esc(category) + '"><span class="project-category-line"></span><span class="project-category-label">' + esc(category) + '</span><span class="project-category-arrow">▼</span><span class="project-category-line"></span></button><div class="project-category-items' + (isCollapsed ? ' collapsed' : '') + '"><div>'; groups[category].forEach(function (project) { html += renderProject(project); }); html += '</div></div>'; });
    html += '<button class="project-row-add" type="button" data-action="add-project">+ 添加项目</button>'; document.getElementById('projectList').innerHTML = html;
  }
  function renderProject(project) {
    var stats = projectStats(project), color = projectColor(project), name = dutyName(project); var badge = name ? '<span class="duty-badge" style="background:' + color + '15;color:' + color + '">' + esc(name) + '</span>' : '';
    var row = '<div class="project-row" style="' + (name ? 'border-left:3px solid ' + color : '') + '"><div class="project-icon-wrap">' + iconMarkup(project) + '</div><div class="project-row-body"><div class="project-row-top"><span class="project-row-name">' + esc(project.name) + '</span>' + badge + (stats.total && stats.collected === stats.total ? '<span class="project-complete-star">★</span>' : '') + '</div><div class="project-row-meta"><span>' + stats.collected + ' / ' + stats.total + '</span><div class="project-row-progress"><div class="project-row-fill" style="width:' + stats.percent + '%;background:linear-gradient(90deg,' + color + ',' + color + 'cc)"></div></div><span class="project-row-pct">' + stats.percent + '%</span></div></div><button class="project-edit-btn" type="button" aria-label="编辑项目" data-action="edit-project" data-project-id="' + esc(project.id) + '">⋯</button></div>';
    return row + '<div class="shop-inline-detail">' + renderProjectItems(project) + '<button class="add-item-btn" type="button" data-action="add-item" data-project-id="' + esc(project.id) + '">+ 添加品目</button></div>';
  }
  function renderProjectItems(project) {
    var sections = project.sections && project.sections.length ? project.sections : [{ name: '', count: project.items.length, cols: 3, tagText: '', tagColor: projectColor(project) }], html = '', offset = 0;
    sections.forEach(function (section) { var count = Math.max(0, Number(section.count) || 0), items = project.items.slice(offset, offset + count), collected = items.filter(function (item) { return isOwned(item.id); }).length, percent = items.length ? Math.round(collected / items.length * 100) : 0;
      if (section.name || sections.length > 1) { var badge = section.tagText ? '<span class="section-type-badge" style="background:' + section.tagColor + '20;color:' + section.tagColor + '">' + esc(section.tagText) + '</span>' : ''; html += '<div class="section-divider"><div class="section-divider-line"></div><div class="section-divider-center"><span class="section-divider-label">' + esc(section.name || '未命名分栏') + badge + '</span><span class="section-progress">' + collected + '/' + items.length + ' ' + percent + '%</span></div><div class="section-divider-line"></div></div>'; }
      var cols = clamp(section.cols || 3, 1, 5); html += '<div class="section-grid' + (cols === 1 ? ' one-column' : '') + '" style="grid-template-columns:repeat(' + cols + ',1fr)">'; items.forEach(function (item, localIndex) { html += renderItemCell(project, item, offset + localIndex); }); html += '</div>'; offset += count;
    });
    if (offset < project.items.length) { html += '<div class="section-grid" style="grid-template-columns:repeat(3,1fr)">'; project.items.slice(offset).forEach(function (item, localIndex) { html += renderItemCell(project, item, offset + localIndex); }); html += '</div>'; }
    if (!project.items.length) html += '<div style="padding:24px 20px;text-align:center;color:#ccc;font-size:11px">还没有品目</div>'; return html;
  }
  function renderItemCell(project, item, index) {
    var owned = isOwned(item.id), image = item.img || item.image || '';
    return '<div class="item-cell' + (owned ? ' collected' : '') + (image ? ' has-img' : '') + '" data-action="open-item" data-project-id="' + esc(project.id) + '" data-item-id="' + esc(item.id) + '">' + (image ? '<img class="item-img" src="' + esc(image) + '" alt="">' : '<span class="item-num">' + (index + 1) + '</span>') + (item.price ? '<span class="item-price">¥' + item.price + '</span>' : '') + '<span class="item-label">' + esc(item.name || ('品目' + (index + 1))) + '</span>' + (owned ? '<span class="item-check">✓</span>' : '') + '</div>';
  }

  function categoryOptions() { var names = []; projects().forEach(function (project) { if (names.indexOf(project.category) < 0) names.push(project.category); }); return names.map(function (name) { return '<option value="' + esc(name) + '"></option>'; }).join(''); }
  function emptySectionDraft() { return { id: gid('shop_section'), name: '', count: 0, cols: 3, tagText: '', tagColor: '#E8B96A', _items: [] }; }
  function buildSectionDrafts(project) { var sections = project.sections && project.sections.length ? project.sections : [{ id: gid('shop_section'), name: '', count: project.items.length, cols: 3, tagText: '', tagColor: projectColor(project) }], offset = 0; return sections.map(function (section) { var count = Math.max(0, Number(section.count) || 0), draft = Object.assign({}, section, { _items: project.items.slice(offset, offset + count) }); offset += count; return draft; }); }
  function renderSectionsEditor() {
    document.getElementById('sectionList').innerHTML = sectionDrafts.map(function (section, index) { var palette = COLORS.map(function (color) { return '<button type="button" class="section-tag-swatch' + (color === section.tagColor ? ' active' : '') + '" style="background:' + color + '" data-action="section-color" data-index="' + index + '" data-color="' + color + '"></button>'; }).join(''), cols = ''; for (var value = 1; value <= 5; value += 1) cols += '<option value="' + value + '"' + (Number(section.cols) === value ? ' selected' : '') + '>' + value + '列</option>';
      return '<div class="section-row"><input type="text" value="' + esc(section.name) + '" placeholder="分栏名称" data-section-field="name" data-index="' + index + '"><button class="del-sec" type="button" data-action="remove-section" data-index="' + index + '">×</button><div class="section-config"><div class="section-config-line"><input type="text" value="' + esc(section.tagText || '') + '" placeholder="如：甜点封面、通勤款" data-section-field="tagText" data-index="' + index + '"><div class="section-tag-palette">' + palette + '</div></div><div class="section-config-line"><span class="section-config-label">内容</span><select disabled><option>商品</option></select><span class="section-config-label">数量</span><input type="number" min="0" max="99" value="' + Math.max(0, Number(section.count) || 0) + '" data-section-field="count" data-index="' + index + '"><select data-section-field="cols" data-index="' + index + '">' + cols + '</select></div></div></div>'; }).join('');
  }
  function renderDuty() {
    var html = DUTY_PRESETS.map(function (item) { var active = dutyDraft.type === item.type; return '<button class="duty-opt' + (active ? ' active' : '') + '" type="button" style="border-color:' + item.color + ';' + (active ? 'background:' + item.color + '15;color:' + item.color : '') + '" data-action="select-duty" data-duty="' + item.type + '">' + item.name + '</button>'; }).join(''); html += '<button class="duty-opt' + (dutyDraft.type === 'custom' ? ' active' : '') + '" type="button" data-action="select-duty" data-duty="custom">其他</button>'; document.getElementById('dutyRow').innerHTML = html;
    document.getElementById('dutyCustomRow').style.display = dutyDraft.type === 'custom' ? 'flex' : 'none'; document.getElementById('dutyCustomName').value = dutyDraft.name || ''; document.getElementById('colorPicker').innerHTML = COLORS.map(function (color) { return '<button type="button" class="color-swatch' + (color === dutyDraft.color ? ' active' : '') + '" style="background:' + color + '" data-action="select-custom-color" data-color="' + color + '"></button>'; }).join('');
  }
  function setIconPreview() { var editor = document.getElementById('projectIconEditor'), preview = document.getElementById('projectIconPreview'); if (projectIconDraft) { preview.src = projectIconDraft; preview.style.objectPosition = projectIconPosition.x + '% ' + projectIconPosition.y + '%'; editor.style.display = 'block'; } else { preview.src = ''; editor.style.display = 'none'; } }
  function openProject(projectId) {
    var project = projectById(projectId); editProjectId = project ? project.id : ''; document.getElementById('projectModalTitle').textContent = project ? '编辑项目' : '添加项目'; document.getElementById('inputProjectName').value = project ? project.name : ''; document.getElementById('inputProjectCategory').value = project ? project.category : ''; document.getElementById('inputProjectNote').value = project ? project.note || '' : ''; document.getElementById('projectCategoryOptions').innerHTML = categoryOptions(); document.getElementById('projectIconInput').value = ''; projectIconDraft = project ? project.icon || project.cover || '' : ''; projectIconPosition = project ? { x: clamp(project.iconPositionX || 50, 0, 100), y: clamp(project.iconPositionY || 50, 0, 100) } : { x: 50, y: 50 }; sectionDrafts = project ? buildSectionDrafts(project) : [emptySectionDraft()]; dutyDraft = project && project.duty ? Object.assign({}, project.duty) : { type: '', name: '', color: '#E8B96A' }; document.getElementById('projectDeleteBtn').style.display = project ? '' : 'none'; setIconPreview(); renderSectionsEditor(); renderDuty(); openModal('projectModal');
  }
  function genericName(name) { return /^品目\s*\d+$/.test(String(name || '')); }
  function itemHasContent(item) { return !!(item && (!genericName(item.name) || item.note || item.description || item.img || item.image || item.price || item.reaction || item.acquiredAt || isOwned(item.id))); }
  function removeSectionDraft(index) {
    if (sectionDrafts.length === 1) { showToast('至少保留一个分栏'); return; }
    var draft = sectionDrafts[index];
    var remove = function () { sectionDrafts.splice(index, 1); renderSectionsEditor(); };
    if (draft && Array.isArray(draft._items) && draft._items.some(itemHasContent)) confirmBox('删除这个分栏以及其中已填写的品目？', remove, { yes: '删除', danger: true });
    else remove();
  }
  function blankItem(number) { return global.CBIData.normalizeShopProjectItem({ id: gid('shop_item'), name: '品目' + number, price: 0, order: number - 1, itemType: 'shopping' }); }
  function finalizedSections() {
    var items = [], sections = []; sectionDrafts.forEach(function (draft) { var requested = Math.max(0, Math.floor(Number(draft.count) || 0)), source = Array.isArray(draft._items) ? draft._items.slice() : [], group = source.slice(0, requested); source.slice(requested).forEach(function (item) { if (itemHasContent(item)) group.push(item); }); while (group.length < requested) group.push(blankItem(items.length + group.length + 1)); group.forEach(function (item) { item.order = items.length; items.push(item); }); if (draft.name || group.length || sectionDrafts.length === 1) sections.push(global.CBIData.normalizeShopSection({ id: draft.id, name: draft.name, count: group.length, cols: draft.cols, tagText: draft.tagText, tagColor: draft.tagColor }, sections.length)); }); if (!sections.length) sections.push(global.CBIData.normalizeShopSection({ name: '', count: 0, cols: 3, tagColor: dutyDraft.color }, 0)); return { sections: sections, items: items };
  }
  async function saveProject() {
    var name = document.getElementById('inputProjectName').value.trim(); if (!name) { showToast('请填写项目名'); return; } if (dutyDraft.type === 'custom') dutyDraft.name = document.getElementById('dutyCustomName').value.trim(); var existing = projectById(editProjectId), stableId = existing ? existing.id : gid('shop_project'), icon = projectIconDraft;
    if (icon && /^data:/.test(icon) && global.CloudSync) { try { icon = await global.CloudSync.uploadDataUrl(icon, 'shop/' + stableId + '_icon.jpg'); } catch (error) {} }
    var final = finalizedSections(), raw = { id: stableId, name: name, category: document.getElementById('inputProjectCategory').value.trim() || '未分类', note: document.getElementById('inputProjectNote').value.trim(), icon: icon, iconPositionX: projectIconPosition.x, iconPositionY: projectIconPosition.y, color: dutyDraft.color, duty: dutyDraft, sections: final.sections, items: final.items, order: existing ? existing.order : projects().length }, normalized = global.CBIData.normalizeShopProject(raw, raw.order);
    if (existing) db.work.shop.projects = projects().map(function (project) { return project.id === existing.id ? normalized : project; }); else db.work.shop.projects.push(normalized); save(); closeModal('projectModal'); render(); showToast(existing ? '项目已更新' : '项目已添加');
  }
  function deleteProject() {
    var project = projectById(editProjectId); if (!project) return; confirmBox('删除「' + project.name + '」以及其中所有品目？', function () { var ids = project.items.map(function (item) { return item.id; }); db.work.shop.projects = projects().filter(function (entry) { return entry.id !== project.id; }); db.work.shop.owned = db.work.shop.owned.filter(function (id) { return ids.indexOf(id) < 0; }); db.work.shop.purchaseLog = db.work.shop.purchaseLog.filter(function (entry) { return ids.indexOf(entry.itemId) < 0; }); save(); closeModal('projectModal'); render(); showToast('项目已删除'); }, { yes: '删除', danger: true });
  }

  function sectionIndexForItem(project, itemId) { var itemIndex = project.items.findIndex(function (item) { return item.id === itemId; }), offset = 0; for (var index = 0; index < project.sections.length; index += 1) { offset += Math.max(0, Number(project.sections[index].count) || 0); if (itemIndex < offset) return index; } return Math.max(0, project.sections.length - 1); }
  function sectionEnd(project, sectionIndex) { var total = 0; for (var index = 0; index <= sectionIndex; index += 1) total += Math.max(0, Number(project.sections[index].count) || 0); return total; }
  function renderItemSectionOptions(project, selected) { if (!project.sections.length) project.sections.push(global.CBIData.normalizeShopSection({ name: '', count: project.items.length, cols: 3 }, 0)); document.getElementById('inputItemSection').innerHTML = project.sections.map(function (section, index) { return '<option value="' + index + '"' + (index === selected ? ' selected' : '') + '>' + esc(section.name || ('分栏 ' + (index + 1))) + '</option>'; }).join(''); }
  function openItemForm(projectId, itemId) {
    var project = projectById(projectId); if (!project) return; var item = itemById(project, itemId); editItemProjectId = project.id; editItemId = item ? item.id : ''; document.getElementById('itemModalTitle').textContent = item ? '编辑品目' : '添加品目'; document.getElementById('inputItemName').value = item ? item.name : ''; document.getElementById('inputItemNote').value = item ? item.note || item.description || '' : ''; document.getElementById('inputItemPrice').value = item ? item.price || 0 : 0; document.getElementById('itemDeleteBtn').style.display = item ? '' : 'none'; document.getElementById('itemImgInput').value = ''; itemImageDraft = item ? item.img || item.image || '' : ''; var preview = document.getElementById('itemImgPreview'); if (itemImageDraft) { preview.src = itemImageDraft; preview.style.display = 'block'; } else { preview.src = ''; preview.style.display = 'none'; } renderItemSectionOptions(project, item ? sectionIndexForItem(project, item.id) : 0); openModal('itemModal');
  }
  async function saveItem() {
    var project = projectById(editItemProjectId); if (!project) return; var existing = itemById(project, editItemId), selected = Math.max(0, Math.min(project.sections.length - 1, Number(document.getElementById('inputItemSection').value) || 0)), stableId = existing ? existing.id : gid('shop_item'), image = itemImageDraft;
    if (image && /^data:/.test(image) && global.CloudSync) { try { image = await global.CloudSync.uploadDataUrl(image, 'shop/' + project.id + '_' + stableId + '.jpg'); } catch (error) {} }
    var note = document.getElementById('inputItemNote').value.trim(), raw = Object.assign({}, existing || {}, { id: stableId, name: document.getElementById('inputItemName').value.trim() || ('品目' + (project.items.length + 1)), note: note, description: note, price: Math.max(0, Math.floor(Number(document.getElementById('inputItemPrice').value) || 0)), img: image, image: image, targetIds: project.duty && NAMES[project.duty.type] ? [project.duty.type] : [], order: 0 }), normalized = global.CBIData.normalizeShopProjectItem(raw);
    if (existing) { var oldIndex = project.items.findIndex(function (item) { return item.id === existing.id; }), oldSection = sectionIndexForItem(project, existing.id); if (oldSection === selected) project.items[oldIndex] = normalized; else { project.items.splice(oldIndex, 1); project.sections[oldSection].count = Math.max(0, project.sections[oldSection].count - 1); var insert = sectionEnd(project, selected); project.items.splice(insert, 0, normalized); project.sections[selected].count += 1; } }
    else { var insertAt = sectionEnd(project, selected); project.items.splice(insertAt, 0, normalized); project.sections[selected].count += 1; }
    project.items.forEach(function (item, index) { item.order = index; }); save(); closeModal('itemModal'); render(); showToast(existing ? '品目已更新' : '品目已添加');
  }
  function deleteItem() {
    var project = projectById(editItemProjectId), item = itemById(project, editItemId); if (!project || !item) return; confirmBox('删除品目「' + item.name + '」？', function () { var sectionIndex = sectionIndexForItem(project, item.id); project.items = project.items.filter(function (entry) { return entry.id !== item.id; }); if (project.sections[sectionIndex]) project.sections[sectionIndex].count = Math.max(0, project.sections[sectionIndex].count - 1); db.work.shop.owned = db.work.shop.owned.filter(function (id) { return id !== item.id; }); db.work.shop.purchaseLog = db.work.shop.purchaseLog.filter(function (entry) { return entry.itemId !== item.id; }); save(); closeModal('itemModal'); render(); showToast('品目已删除'); }, { yes: '删除', danger: true });
  }
  function openItemDetail(projectId, itemId) {
    var project = projectById(projectId), item = itemById(project, itemId); if (!project || !item) return; editItemProjectId = project.id; editItemId = item.id; var owned = isOwned(item.id), fund = availableFund(), image = item.img || item.image || ''; document.getElementById('itemDetailTitle').textContent = owned ? '已获得品目' : '品目打卡'; document.getElementById('itemDetailBody').innerHTML = '<div class="item-detail"><div class="item-detail-preview">' + (image ? '<img src="' + esc(image) + '" alt="">' : '◇') + '</div><h3>' + esc(item.name) + '</h3><div class="item-detail-meta">' + esc(dutyName(project) || '未指定') + (item.price ? ' · ¥' + item.price : '') + '</div>' + (item.note || item.description ? '<div class="item-detail-note">' + esc(item.note || item.description) + '</div>' : '') + '<div class="fund-note">当前商城资金 ¥' + fund + (owned ? ' · 已点亮' : (item.price > fund ? ' · 余额不足' : ' · 点亮后从娱乐差额中结算')) + '</div></div>'; var actions = '<button class="btn btn-cancel" type="button" data-close="itemDetailModal">关闭</button><button class="btn btn-cancel" type="button" data-action="edit-current-item">编辑</button>'; actions += owned ? '<button class="btn btn-del" type="button" data-action="unacquire-item">取消点亮</button>' : '<button class="btn btn-primary" type="button" data-action="acquire-item"' + (item.price > fund ? ' disabled style="background:#eee;color:#aaa"' : '') + '>购买并点亮</button>'; document.getElementById('itemDetailActions').innerHTML = actions; openModal('itemDetailModal');
  }
  function acquireItem() { var project = projectById(editItemProjectId), item = itemById(project, editItemId); if (!item || isOwned(item.id)) return; if (item.price > availableFund()) { showToast('商城资金不足'); return; } var acquiredAt = new Date().toISOString(); db.work.shop.owned.push(item.id); item.acquiredAt = acquiredAt; item.collected = true; db.work.shop.purchaseLog.push({ itemId: item.id, price: item.price, purchasedAt: acquiredAt, source: 'entertainment_balance' }); save(); closeModal('itemDetailModal'); render(); showToast('品目已点亮 · ¥' + item.price); }
  function unacquireItem() { var project = projectById(editItemProjectId), item = itemById(project, editItemId); if (!item || !isOwned(item.id)) return; confirmBox('取消点亮「' + item.name + '」并退回这笔商城资金？', function () { db.work.shop.owned = db.work.shop.owned.filter(function (id) { return id !== item.id; }); db.work.shop.purchaseLog = db.work.shop.purchaseLog.filter(function (entry) { return entry.itemId !== item.id; }); item.acquiredAt = ''; item.collected = false; save(); closeModal('itemDetailModal'); render(); showToast('已取消点亮'); }, { yes: '取消点亮', danger: true }); }

  function optimizedImage(file, maxSide) { return new Promise(function (resolve, reject) { var reader = new FileReader(); reader.onerror = reject; reader.onload = function () { var image = new Image(); image.onerror = reject; image.onload = function () { var scale = Math.min(1, (maxSide || 1200) / Math.max(image.width, image.height)), canvas = document.createElement('canvas'); canvas.width = Math.max(1, Math.round(image.width * scale)); canvas.height = Math.max(1, Math.round(image.height * scale)); canvas.getContext('2d').drawImage(image, 0, 0, canvas.width, canvas.height); resolve(canvas.toDataURL('image/jpeg', .86)); }; image.src = reader.result; }; reader.readAsDataURL(file); }); }
  function projectIconSelected(input) { if (!input.files || !input.files[0]) return; optimizedImage(input.files[0], 1200).then(function (data) { projectIconDraft = data; projectIconPosition = { x: 50, y: 50 }; setIconPreview(); }).catch(function () { showToast('图片读取失败'); }); }
  function itemImageSelected(input) { if (!input.files || !input.files[0]) return; optimizedImage(input.files[0], 1200).then(function (data) { itemImageDraft = data; var preview = document.getElementById('itemImgPreview'); preview.src = data; preview.style.display = 'block'; }).catch(function () { showToast('图片读取失败'); }); }
  function bindIconDrag() { var frame = document.getElementById('projectIconPosFrame'); frame.addEventListener('pointerdown', function (event) { if (event.target.closest('button') || !projectIconDraft) return; iconDrag = { id: event.pointerId, x: event.clientX, y: event.clientY, baseX: projectIconPosition.x, baseY: projectIconPosition.y }; try { frame.setPointerCapture(event.pointerId); } catch (error) {} }); frame.addEventListener('pointermove', function (event) { if (!iconDrag || iconDrag.id !== event.pointerId) return; var rect = frame.getBoundingClientRect(); projectIconPosition.x = clamp(iconDrag.baseX - (event.clientX - iconDrag.x) / rect.width * 100, 0, 100); projectIconPosition.y = clamp(iconDrag.baseY - (event.clientY - iconDrag.y) / rect.height * 100, 0, 100); document.getElementById('projectIconPreview').style.objectPosition = projectIconPosition.x + '% ' + projectIconPosition.y + '%'; }); frame.addEventListener('pointerup', function () { iconDrag = null; }); frame.addEventListener('pointercancel', function () { iconDrag = null; }); }
  function bindTabSwipe() {
    document.addEventListener('touchstart', function (event) {
      var blocked = event.target.closest && event.target.closest('input,textarea,select,button,a,[contenteditable="true"],.modal-bg.show,.project-icon-pos-frame');
      if ((global.innerWidth || 0) > 720 || event.touches.length !== 1 || blocked) { shopSwipeStart = null; return; }
      shopSwipeStart = { x: event.touches[0].clientX, y: event.touches[0].clientY, at: Date.now() };
    }, { passive: true });
    document.addEventListener('touchend', function (event) {
      if (!shopSwipeStart || !event.changedTouches.length) return;
      var start = shopSwipeStart;
      shopSwipeStart = null;
      var dx = event.changedTouches[0].clientX - start.x;
      var dy = event.changedTouches[0].clientY - start.y;
      if (Date.now() - start.at <= 900 && dx >= 58 && Math.abs(dx) > Math.abs(dy) * 1.25) global.location.href = 'wallet.html#reimbursement';
    }, { passive: true });
    document.addEventListener('touchcancel', function () { shopSwipeStart = null; }, { passive: true });
  }
  function exportShop() { var blob = new Blob([JSON.stringify(db.work.shop, null, 2)], { type: 'application/json' }), link = document.createElement('a'); link.href = URL.createObjectURL(blob); link.download = 'shop_backup_' + today() + '.json'; link.click(); }
  function importShop(input) { if (!input.files || !input.files[0]) return; var reader = new FileReader(); reader.onload = function () { try { var parsed = JSON.parse(reader.result); confirmBox('导入商城备份并覆盖当前商城内容？', function () { db.work.shop = global.CBIData.normalizeShop(parsed); save(); closeModal('backupModal'); render(); showToast('商城备份已导入'); }, { yes: '导入' }); } catch (error) { showToast('备份格式不正确'); } input.value = ''; }; reader.readAsText(input.files[0]); }

  function handleClick(event) {
    var close = event.target.closest('[data-close]'); if (close) { closeModal(close.dataset.close); return; } var target = event.target.closest('[data-action]'); if (!target) return; var action = target.dataset.action;
    if (action === 'toggle-category') { collapsed[target.dataset.category] = collapsed[target.dataset.category] !== true; saveCollapsed(); render(); }
    else if (action === 'add-project') openProject(''); else if (action === 'edit-project') openProject(target.dataset.projectId); else if (action === 'save-project') saveProject(); else if (action === 'delete-project') deleteProject();
    else if (action === 'add-section') { sectionDrafts.push(emptySectionDraft()); renderSectionsEditor(); } else if (action === 'remove-section') removeSectionDraft(Number(target.dataset.index)); else if (action === 'section-color') { sectionDrafts[Number(target.dataset.index)].tagColor = target.dataset.color; renderSectionsEditor(); }
    else if (action === 'select-duty') { var preset = DUTY_PRESETS.find(function (item) { return item.type === target.dataset.duty; }); dutyDraft = preset ? { type: preset.type, name: preset.name, color: preset.color } : { type: 'custom', name: dutyDraft.name || '', color: dutyDraft.color || '#E8B96A' }; renderDuty(); } else if (action === 'select-custom-color') { dutyDraft.color = target.dataset.color; renderDuty(); }
    else if (action === 'clear-project-icon') { event.stopPropagation(); projectIconDraft = ''; projectIconPosition = { x: 50, y: 50 }; setIconPreview(); } else if (action === 'reset-project-icon') { projectIconPosition = { x: 50, y: 50 }; setIconPreview(); }
    else if (action === 'add-item') openItemForm(target.dataset.projectId, ''); else if (action === 'open-item') openItemDetail(target.dataset.projectId, target.dataset.itemId); else if (action === 'save-item') saveItem(); else if (action === 'delete-item') deleteItem(); else if (action === 'edit-current-item') { closeModal('itemDetailModal'); openItemForm(editItemProjectId, editItemId); } else if (action === 'acquire-item') acquireItem(); else if (action === 'unacquire-item') unacquireItem();
    else if (action === 'backup') openModal('backupModal'); else if (action === 'export-shop') exportShop(); else if (action === 'import-shop') document.getElementById('shopImportInput').click();
  }
  function handleInput(event) { var field = event.target.dataset.sectionField; if (!field) return; var draft = sectionDrafts[Number(event.target.dataset.index)]; if (!draft) return; draft[field] = field === 'count' || field === 'cols' ? Math.max(0, Number(event.target.value) || 0) : event.target.value; }
  function mount() {
    if (!global.CBIData) return false; document.body.dataset.cbiShop = '3'; injectStyles(); shell(); db = global.CBIData.load(); collapsed = loadCollapsed(); document.title = 'Shop · Crossworld Window'; document.body.addEventListener('click', handleClick); document.body.addEventListener('input', handleInput); document.querySelectorAll('.modal-bg').forEach(function (modal) { modal.addEventListener('click', function (event) { if (event.target === modal) closeModal(modal.id); }); }); document.getElementById('projectIconInput').addEventListener('change', function () { projectIconSelected(this); }); document.getElementById('itemImgInput').addEventListener('change', function () { itemImageSelected(this); }); document.getElementById('shopImportInput').addEventListener('change', function () { importShop(this); }); bindIconDrag(); bindTabSwipe(); render(); return true;
  }
  global.CBIShop = Object.freeze({ mount: mount });
})(window);
